# Generated by Django 4.1.7 on 2023-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_settings_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="defaultSoundName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="defaultSoundUrl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
